using System.Text.Json.Serialization;

namespace AirportControlTower.API.Models
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum AirlineState : byte { Parked = 1, TakingOff = 2, Airborne = 3, Approach = 4, Landed = 5 }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum AirlineStateTrigger : byte { Park = 1, TakeOff = 2, IsAirborne = 3, Approach = 4, Land = 6, Abort = 7 }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum AirlineType : byte { Airliner = 1, Private = 2 }

    public class Airline
    {
        public Guid Id { get; set; }
        public required string Name { get; set; }

        //Assumed that callsign is generated by the control tower and communicated to airline
        public AirlineState State { get; set; }
        public AirlineType Type { get; set; }
        public required string CallSign { get; set; }
        public Position LastKnownPosition { get; set; } = default!;
        public DateTime LastUpdate { get; set; }
       
        public ICollection<StateChangeHistory> StateHistory { get; set; } = [];
    }

    public class Position
    {
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public float Altitude { get; set; }
        public float Heading { get; set; }
    }
}
